name: Fetching Bus Data
on: 
  push:
  schedule:
    - cron: "00 05 * * *"
jobs:
  Fetch-Bus-Data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
            python-version: '3.8'
            architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Crawling resources
        run: |
          python kmb.py
